name: Basic Workflow
on: [push]

jobs:
  basic-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # First, we need to checkout the repo
      uses: actions/checkout@v4

    - name: Get started
      # Just so we see that things work
      run: echo "Ready? Let's start 🚀"

    - name: Unmask the secret
      # Calling the unmasking action
      uses: ./.github/actions/unmask_secret
      id: unmask-secret
      with:
        # Providing the secret as an input
        de-value: ${{ secrets.SOME_SECRET }}

    - name: Print unmasked secret
      # Fetching the output and printing it
      run: |
        echo "(Calling workflow) Unmasked value is: ${{ steps.unmask-secret.outputs.unmasked-value }}"
        echo "(Calling workflow) First half on unmasked value is: ${{ steps.unmask-secret.outputs.first-half }}"
        echo "(Calling workflow) 2nd half on unmasked value is: ${{ steps.unmask-secret.outputs.second-half }}"

    - name: Same works for variables as well
      uses: ./.github/actions/unmask_secret
      id: unmask-value
      with:
        de-value: ${{ vars.SOME_VAR }}

    - name: Print unmasked variable
      run: echo "(Calling workflow) ${{ steps.unmask-value.outputs.unmasked-value }}"
